#!/bin/bash
#set -x
scriptdir=$(dirname $(realpath $0))
configdir=$scriptdir/config

LIFETIMESTART=${LIFETIMESTART:-/tmp/$USER.lifetimestart}
DEFAULTLIFETIME=$(( 60 * 60 * 12 ))
DEFAULTWARNINGLIFETIME=$(( 60 * 60 * 6 ))
MAXLIFETIME=$1
WARNINGLIFETIME=$2

if [[ -z $MAXLIFETIME ]]; then
    if  [[ -a $configdir/maxlifetime_sec ]]; then
        MAXLIFETIME=$(cat $configdir/maxlifetimesec)
    else
        MAXLIFETIME=$DEFAULTLIFETIME
    fi    
fi

if [[ -z $WARNINGLIFETIME ]]; then
    if  [[ -a $configdir/warninglifetime_sec ]]; then
        WARNINGLIFETIME=$(cat $configdir/warninglifetimesec)
    else
        WARNINGLIFETIME=$DEFAULTWARNINGLIFETIME
    fi    
fi

if [[ ! -a $LIFETIMESTART ]]; then
    echo $now > $LIFETIMESTART
else
    start=$(cat $LIFETIMESTART)
    diff=$(( now - start ))
    if (( diff % WARNINGPERIOD == 0 )); then
	$scriptdir/onlifetimewarning
    fi
    if (( diff > MAXLIFETIME )); then
	$scriptdir/onlifetimeexceed
	exit -1
    fi
fi
exit 0
