#!/bin/bash

scriptdir=$(dirname $(realpath $0))
configdir=$scriptdir/config

LASTIDLE=${LASTIDLE:-/tmp/$USER.lastidle}
LIFETIMESTART=${LIFETIMESTART:-/tmp/$USER.lifetimestart}
DEFAULTIDLESEC=$(( 60 * 30 ))
DEFAULTLIFETIME=$(( 60 * 60 * 24 ))

if [[ -a $LASTIDLE ]]; then
  last=$(cat $LASTIDLE)
fi

group=${1:-data}
users=$(grep ^$group /etc/group)
users=${users##*:}
IDLESEC=$2
MAXLIFETIME=$3
WARNINGPERIOD=$4

# if we exceed max life time then we force idle behaviour
if [[ ! -a $LIFETIMESTART ]]; then
    echo $now > $LIFETIMESTART
else
    start=$(cat $LIFETIMESTART)
    if (( (now - start) > MAXLIFETIME )); then
	exit 0
    fi
fi
