#!/bin/bash
#set -x

scriptdir=$(dirname $(realpath $0))
configdir=$scriptdir/config

# if we are forced not to check idle then always return -1 
[[ -a $configdir/forcenoidle ]] && exit -1

LASTIDLE=${LASTIDLE:-/tmp/$USER.lastidle}
DEFAULTIDLESEC=$(( 60 * 30 ))

if [[ -a $LASTIDLE ]]; then
  last=$(cat $LASTIDLE)
fi


IDLESEC=$1

if [[ -z $IDLESEC ]]; then
    if  [[ -a $configdir/idlesec ]]; then
        IDLESEC=$(cat $configdir/idlesec)
    else
        IDLESEC=$DEFAULTIDLESEC
    fi
else
    shift
fi

if [[ -a $connfigdir/idleusers ]]; then
    users=$(cat $configdir/idleusers)
fi

if [[ -n "$@" ]]; then
    # extra command line arguments are assumed to be additional users users
    if [[ -z $users ]]; then
	users="$@"
    else 
	users="$users $@"
    fi
fi

if [[ -a $configdir/idlegroup ]]; then
    group=$(cat $configdir/idlegroup)
    grpusers=$(grep ^$group /etc/group)
    grpusers=${grpusers##*:}
    grpusers=${grpusers//,/ }
    if [[ -z $users ]]; then
	users="$grpusers"
    else
	users="$users $grpusers"
    fi
fi

if [[ -z $users ]]; then
    n=0
else
    n=$(ps u --no-header  -u ${users// / -u } | wc -l)
fi

now=$(date +%s)

if (( n == 0 )); then
   if [[ -n $last ]]; then
       diff=$(( now - last ))
       if (( diff > IDLESEC )); then
	   echo "now:$now last:$last diff:$diff" > /tmp/$USER.idle.info
           exit 0
       fi
   else
       echo $now > $LASTIDLE
   fi
else
   [[ -a $LASTIDLE ]] && rm $LASTIDLE
fi

exit -1
