#!/bin/bash
#set -x
NUM_RETRY=10
OSCMD=${OSCMD:-openstack}

scriptdir=$(dirname $(realpath $0))
configdir=$scriptdir/config

if [[ -z $CREDRC ]] && [[ -a $configdir/default_cred.rc ]]; then
   CREDRC=$configdir/default_cred.rc
fi
if [[ -z $CREDRC ]]; then
  echo "$0: ERROR: no credential rc file specified via CREDRC environment variable and no default configured." > /dev/stderr
  exit -1
fi   

source $CREDRC

server=$1

if [[ -z $server ]] && [[ -a $configdir/default_server ]]; then
   server=$(cat $configdir/default_server)
fi
if [[ -z $server ]]; then
  echo "$0: ERROR: no server instance specified and no default configured"
  exit -1
fi


#if ! $OSCMD server ssh $server -- -l $user true; then
  for ((i=0; i<$NUM_RETRY; i++)); do
      status=$($OSCMD server show -c status -f value $server)

      if [[ $status == "ACTIVE" ]]; then
 	break;
      fi
   done
#else 
shift

exec $OSCMD server ssh $server -- $@
fi
