#!/bin/bash
#set -x
# not we force no strict host key checking as when VM's get rebuilt their
# host keys will often get regenerated
OPENSTACKSSH_NUM_RETRY=${OPENSTACKSSH_NUM_RETRY:-10}
# comment next line to permit known_host update
OPENSTACKSSH_NO_KNOWNHOSTS=${OPENSTACKSSH_NO_KNOWNHOSTS:-1}
OPENSTACKSSH_SLEEP=${OPENSTACKSSH_SLEEP:-$((60 * 1))}
OSCMD=${OSCMD:-openstack}

scriptdir=$(dirname $(realpath $0))
configdir=$scriptdir/config

if [[ -z $CREDRC ]] && [[ -a $configdir/default_cred.rc ]]; then
   CREDRC=$configdir/default_cred.rc
fi
if [[ -z $CREDRC ]]; then
  echo "$0: ERROR: no credential rc file specified via CREDRC environment variable and no default configured." > /dev/stderr
  exit -1
fi   

source $CREDRC

server=$1

if [[ -z $server ]] && [[ -a $configdir/default_server ]]; then
   server=$(cat $configdir/default_server)
fi
if [[ -z $server ]]; then
  echo "$0: ERROR: no server instance specified and no default configured"
  exit -1
fi

# simple way to test if the ssh server is up is to use an ssh command
# that is known to fail due to bad authentication or other user error
# with a short connection time out... this way if the system is down
# we can figure it out quickly ... however if it is up then we will
# fail quickly due an early rejection... at least that my story and
# I am sticking to it ;-)
function isup()
{
#    set -x
    local s=$1
    local out
    local rc=0
    
    #! $OSCMD server ssh $s -- -l nobody -i /dev/null -v -o "StrictHostKeyChecking no" ConnectTimeout=1 -o ConnectTimeout=1 -o ConnectionAttempts=1 true 2>&1 | grep -i  "timed out"
    # not sure if we really need  ConnectionAttempts=1 so default behaviour for the moment is not to use it
    if [[ -z ${OPENSTACKSSH_NO_KNOWNHOSTS} ]]; then
	# rather than ignoring known_host logic we changed our approach to removing it from known hosts when we recreate the vm and if this proves to not work stably the
	out=$($OSCMD server ssh $s -- -l nobody -i /dev/null -v -o ConnectTimeout=1 true 2>&1)
    else
	# following ignores known_hosts and avoids a new entry for the host
	out=$($OSCMD server ssh $s -- -l nobody -i /dev/null -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ConnectTimeout=1 true 2>&1)
    fi
    if [[ $out =~ ^No\ server.*$ ]]; then
	rc=1
    elif [[ $out =~ ^.*Operation\ timed\ out.* ]]; then
	rc=2
    else
	rc=0
    fi
    return $rc
}

for ((i=0; i<OPENSTACKSSH_NUM_RETRY; i++)); do
    isup $server
    case $? in
	0)
	    # server is up so we don't need to loop
	    break;
	    ;;
	1)
	    # server does not exist so we must create it.  creation also starts
	    [[ -z $OPENSTACKSSH_SILENT ]] && echo "$server does not EXIST ...creating and starting it up... be patient" > /dev/stderr
	    [[ -z $CREATE_ARGS && -a $configdir/$server ]] && . $configdir/$server
	    # recreating the vm causes its host key to be regenerated.  This is a pain as it will cause ssh to reject connections
	    # as the old entry for the host is not correct.  To make out lives easier we remove the host from the known_host file -- this avoids us having to ignore known_hosts logic
	    ssh-keygen -R $server
	    ssh-keygen -R $FLOAT_IP
	    $OSCMD server create --wait --security-group default  --security-group ssh_only $CREATE_ARGS $server
	    [[ -n $FLOAT_IP ]] && $OSCMD server add floating ip $server $FLOAT_IP
	    ;;
	2)
	    # server exists but does not seem to be started
	    [[ -z $OPENSTACKSSH_SILENT ]] && echo "$server is not ACTIVE...starting it up... be patient" > /dev/stderr
	    if $OSCMD server start $server 2>&1 > /dev/stderr; then
		[[ -z $OPENSTACKSSH_SILENT ]] && echo "Sent start command : $OSCMD server start $server" > /dev/stderr
	    else
		[[ -z $OPENSTACKSSH_SILENT ]] && echo "Start command failed will try again if needed" > /dev/stderr
	    fi
	    ;;
    esac
    [[ -z $OPENSTACKSSH_SILENT ]] && echo "sleeping for $OPENSTACKSSH_SLEEP seconds .... while we wait for the system come back up" > /dev/stderr
    sleep $OPENSTACKSSH_SLEEP 
done

if ((i==OPENSTACKSSH_NUM_RETRY)); then
    echo "WTF!!! Was not able to start $server or at least not confirm it is ACTIVE" > /dev/stderr
    exit -1
fi
shift

if [[ -z ${OPENSTACKSSH_NO_KNOWNHOSTS} ]]; then
    # rather than ignoring known_host logic we changed our approach to removing it from known hosts when we recreate the vm and if this proves to not work stably the
    exec $OSCMD server ssh $server -- $@
else 
    # following ignores known_hosts and avoids a new entry for the host
    exec $OSCMD server ssh $server -- -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null  $@
fi
